# Generated by Django 6.0.4 on 2026-05-07 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchens", "0003_alter_kitchen_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchen",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="kitchen",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="kitchen",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="kitchen",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="kitchens/"),
        ),
        migrations.AlterField(
            model_name="kitchen",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kitchen",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
