# Generated by Django 6.0.4 on 2026-05-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchens", "0004_kitchen_description_kitchen_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitchen",
            name="status",
            field=models.BooleanField(),
        ),
    ]
