# Generated by Django 6.0.4 on 2026-05-01 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kitchens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Avaliação não pode ser inferior a 1 estrelas"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, "Avaliação não pode ser superior a 5 estrelas"
                            ),
                        ]
                    ),
                ),
                (
                    "kitchen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="kitchens.kitchen",
                    ),
                ),
            ],
        ),
    ]
