# Generated by Django 6.0.4 on 2026-05-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
