# Generated by Django 6.0.4 on 2026-05-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_rename_update_at_menu_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
